---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: minio-centos8
    box: centos/8
provisioner:
  name: ansible
verifier:
  name: ansible
lint: ansible-lint .
