---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: minio-fedora35
    box: fedora/35-cloud-base
    memory: 1024
  - name: minio-fedora34
    box: fedora/34-cloud-base
    memory: 1024
  - name: minio-centos8
    box: centos/8
    memory: 1024
  - name: minio-rhel8
    box: generic/rhel8
    memory: 1024
    groups:
      - rhel
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: group_vars
  playbooks:
    prepare: prepare.yml
    cleanup: cleanup.yml
verifier:
  name: ansible
lint: ansible-lint .
